Repository prgrms-web-devcourse/We-are-the-MASTERS-OF-HTTP, pull requests merged in 2023-02, with the labels that each got.

#51 quiz: 6주차 퀴즈 추가 (Hyevvy)
  6주차/hyevvy.md
Labels: 6주차, 클라이언트 식별과 쿠키

#54 quiz: 6주차 퀴즈 추가 (allgold)
  6주차/allgold.md
Labels: 6주차, 클라이언트 식별과 쿠키

#55 quiz: 5주차 퀴즈 추가
  5주차/green.md
Labels: 5주차, 웹 로봇, HTTP/2.0

#56 quiz: 6주차 퀴즈 추가 (green)
  6주차/green.md
Labels: 6주차, 클라이언트 식별과 쿠키

#59 quiz: 6주차 퀴즈 추가 (sonny)
  6주차/sonny.md
Labels: 6주차, 클라이언트 식별과 쿠키

#63 quiz: 7주차 퀴즈 추가
  .github/7주차/green.md
Labels: 7주차, 기본인증

#64 quiz: 7주차 퀴즈 추가(Hyevvy)
  7주차/hyevvy.md
Labels: 7주차, 기본인증

#72 quiz: 8주차 퀴즈 추가 (allgold)
  8주차/allgold.md
Labels: 8주차, 엔터티와 인코딩

#73 quiz: 8주차 퀴즈 추가
  .github/8주차/green.md
Labels: 8주차, 엔터티와 인코딩
